-- =========================================================
-- ERP METAL RACING
-- FINANCEIRO - CONTAS A PAGAR
-- =========================================================

create table if not exists public.contas_pagar (
    id bigint generated by default as identity primary key,

    fornecedor_id bigint null,
    fornecedor_nome text,

    nfe_id bigint null,
    nfe_numero text,
    nfe_chave text,

    numero_titulo text not null,
    numero_parcela text,

    descricao text,

    valor numeric(15,2) not null default 0,
    valor_pago numeric(15,2) not null default 0,

    data_emissao date,
    data_vencimento date,
    data_pagamento date,

    status text not null default 'PENDENTE',

    forma_pagamento text,
    conta_financeira text,
    centro_custo text,

    juros numeric(15,2) not null default 0,
    multa numeric(15,2) not null default 0,
    desconto numeric(15,2) not null default 0,

    observacao text,

    origem text default 'MANUAL',

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_contas_pagar_status
    on public.contas_pagar(status);

create index if not exists idx_contas_pagar_vencimento
    on public.contas_pagar(data_vencimento);

create index if not exists idx_contas_pagar_fornecedor
    on public.contas_pagar(fornecedor_id);

create index if not exists idx_contas_pagar_nfe
    on public.contas_pagar(nfe_id);

create index if not exists idx_contas_pagar_chave_nfe
    on public.contas_pagar(nfe_chave);

comment on table public.contas_pagar is
'Contas a pagar do ERP Metal Racing, incluindo títulos originados de NF-e de entrada.';
